### ISSUE TITLE
Is MyData not populating the 'content_type' field when creating ObjectACLs?

### ISSUE THREAD

**Issue by wettenhj** [monash-merc/mydata#64]
I thought this had been fixed already, but this exception occurred at 15:09 on 2015-07-09:
```
  File "/home/mytardis/mytardis/tardis/tardis_portal/api.py", line 1090, in hydrate
    if bundle.data['content_type'] == 'experiment':

KeyError: 'content_type'


<WSGIRequest
path:/api/v1/objectacl/,
```

**Comment by wettenhj** [comment]
Relevant code: https://github.com/monash-merc/mydata/blob/master/mydata/models/objectacl.py#L38

**Comment by wettenhj** [comment]
```
Internal Server Error: /experiment/control_panel/22/access_list/group/readonly/
Traceback (most recent call last):
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/mytardis/mytardis/tardis/tardis_portal/views.py", line 2079, in retrieve_access_list_group_readonly
    experiment_id)
  File "/home/mytardis/mytardis/tardis/tardis_portal/managers.py", line 289, in group_acls_system_owned
    aclOwnershipType=ObjectACL.SYSTEM_OWNED)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/query.py", line 679, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/query.py", line 697, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1309, in add_q
    clause, require_inner = self._add_q(where_part, self.used_aliases)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1337, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1199, in build_filter
    lookups, value)
  File "/home/mytardis/virtualenvs/mytardis/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 1772, in get_lookup_constraint
    raise TypeError('Related Field got invalid lookup: %s' % lookup_type)
TypeError: Related Field got invalid lookup: name
```

**Comment by wettenhj** [comment]
content_type="experiment" was already included in the JSON POSTed to the MyTardis API for creating ObjectACLs when they were used to share en expeirment with an individual user, but it was not included when creating an ObjectACL to share an experiment with a group.  This has been fixed in: https://github.com/monash-merc/mydata/commit/de31cfb93f28660c34055948a2c248ec34bf0546
